name:                xmobar-config
version:             0.1.0.0
author:              "Andrea Jemmett"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         My personal xmobar configurations

dependencies:
- base >= 4.7 && < 5
- xmobar

library:
  source-dirs: src

executables:
  xmobar-top:
    main:                Top.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -main-is Top
    dependencies:
    - xmobar-config
